services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env    # POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    environment:
      # Перекрываем DATABASE_URL на Postgres
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres

  worker:
    depends_on:
      - postgres

  beat:
    depends_on:
      - postgres

volumes:
  pgdata: {}  # том для PostgreSQL
  