services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build:
      context: .
    env_file: .env
    volumes:
      - ./data:/app/data
    entrypoint: []
    command: celery worker --app=colossus --loglevel=INFO
    depends_on:
      - rabbitmq
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"

  beat:
    build:
      context: .
    env_file: .env
    volumes:
      - ./data:/app/data
    entrypoint: []
    command: celery beat --app=colossus --loglevel=INFO
    depends_on:
      - rabbitmq
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
